### ISSUE TITLE
Context best practice

### ISSUE THREAD

**Issue by geoffwhittington** [sarang0909/Question-Answer-System#1]
This is an interesting implementation: I tried it out and had some success with a simple context. Can you provide some best practices to follow when crafting a context for this system? I started to copy/paste text from Wikipedia and the system's effectiveness started to degrade.

Thanks for posting this repo!

**Comment by sarang0909** [comment]
We have used BERT which is trained on 512 token length. That means it expects context of  512 words/token. So when you try to give context more than 512 words,you'll get erratic answers. Question-Answer system in NLP world are still not advanced enough to accept whole pages/large context. Research is going on and if you are interested you can check Google's Question Answering challenge on Kaggle.com.  For now stick with context length of 512.

**Comment by geoffwhittington** [comment]
Thank you for your response. I presume the best way to improve answers, then, is to explicitly train the system with questions/answers outside of a context?

**Comment by sarang0909** [comment]
Currently,we can not built a system which can answer outside of a context. However,we can broaden the context(currently limited to 512 token).As I mentioned earlier,research is still going on this area.Please do share your insights here if you participate in the research or find anything interesting.

**Comment by geoffwhittington** [comment]
Will do. Thanks for your time and for sharing your code!
